config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :clients do
    collection do
      get 'search'
    end
  end

  resources :vouchers

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/voucher.rb
class Voucher < ApplicationRecord
  validates_presence_of :client_id,
                        :creating_branch_id

  validates :original_balance, numericality: {only_integer: true, greater_than: 0}

  def original_balance_in_euros
    BigDecimal(original_balance || 0) / 100
  end

  #TODO: Make sure euros is only taken as two decimal places
  def original_balance_in_euros=(euros)
    self.original_balance = (BigDecimal(euros) * 100).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def search
    # Make sure at least one field is filled in
    if search_params.to_h.select {|key, value| value.present? }.count < 1
      @empty_search = true
      @clients = []
    else
      @empty_search = false
      # used to populate the search form
      @search = OpenStruct.new(params)
      @result = PhorestGatewayService.new.clients(search_params.to_h)
      @clients = @result[:clients]
      @page = @result[:page]
      # Page index starts at zero, but we want to show the first page as 1
      @current_page_number = (@page[:number] || 0) + 1
    end
    render :search, locals: {search_params: search_params}
  end

  def show
    @client = PhorestGatewayService.new.client(params[:id])
  end

  private

  def search_params
    params.permit(:firstName, :lastName, :email, :page)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/vouchers_controller.rb
class VouchersController < ApplicationController
  def new
    @voucher = Voucher.new(client_id: params[:client_id])
  end

  # Creates a voucher that is saved in our database.
  # Also handles the responsibility of triggering the async update
  # to the phorest API. Should the responsibilties of the controller grow
  # we can break this logic out into a service.
  def create
    automated_params = {
      creating_branch_id: ENV.fetch('PHOREST_BRANCH_ID'),
      serial_number: "in-branch-#{SecureRandom.uuid}"
    }
    @voucher = Voucher.create(voucher_params.merge(automated_params))
    if @voucher.valid?
      SyncVoucher.perform_async(@voucher.id)
      redirect_to voucher_path(@voucher)
    else
      render :new
    end
  end

  def index
    @vouchers = Voucher.all
  end

  def show
    @voucher = Voucher.find(params[:id])
  end

  private

  def voucher_params
    params.require(:voucher).permit(:expiry_date, :issue_date, :original_balance_in_euros, :client_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/views/clients/search.html.erb
<% if @clients.count > 0 %>
  <table>
    <thead>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Actions</th>
    </thead>
    <tbody>
    <% @clients.each do |c| %>
      <tr>
        <td><%= c[:firstName] %></td>
        <td><%= c[:lastName] %></td>
        <td><%= c[:email] %></td>
        <td>
          <%= link_to 'View', client_path(c[:clientId]) %>
        </td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td>
          <% if @current_page_number > 1 %>
            <%= link_to 'Prev', search_clients_path(search_params.merge(page: @page[:number] - 1)) %>
          <% end %>
        </td>
        <td colspan="2">Current Page: <%= @current_page_number %> </td>
        <td>
          <% if @current_page_number < @page[:totalPages] %>
            <%= link_to 'Next', search_clients_path(search_params.merge(page: @page[:number] + 1)) %>
          <% end %>
        </td>
      </tr>
    </tfoot>
  </table>
<% else %>
  <% if @empty_search %>
    <p> Please enter either first name, last name or email at the top of the screen </p>
  <% else %>
    <p> No results found </p>
  <% end %>
<% end %>

app/views/clients/show.html.erb
<section class="client-profile">
  <div class="personal-details">
    <span>Name: <%= @client[:firstName] %> <%= @client[:lastName] %></span>
    <span>Gender: <%= @client[:gender] %> </span>
  </div>
  <div class="salon-details">
    TODO: List vouchers
    <%= link_to 'Create Voucher', new_voucher_path(client_id: @client[:clientId])%>
  </div>
</section>

app/views/home/index.html.erb
<p >Please enter your search terms at the top</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Big Hairy Vouchers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <a class="logo" href="/">
        <img src="<%= asset_path 'phorest-acorn-logo.svg' %>" />
      </a>
      <form action="/clients/search" method="get">
        <input name="firstName" placeholder="first name..." value="<%= @search&.firstName %>"/>
        <input name="lastName" placeholder="last name..." value="<%= @search&.lastName %>"/>
        <input name="email" placeholder="email.." value="<%= @search&.email %>"/>
        <input type="submit" value="Search" />
      </form>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/vouchers/index.html.erb
<table>
  <thead>
    <th>Serial Number</th>
    <th>Client Id</th>
    <th>Original Amount</th>
  </thead>
  <tbody>
    <% @vouchers.each do |v| %>
      <td><%= v.serial_number %><td>
      <td><%= v.client_id %><td>
      <td><%= v.original_balance_in_euros %><td>
    <% end %>
  </tbody>
</table>

app/views/vouchers/new.html.erb
<% if @voucher.errors.count > 0 %>
  <div class="feedback error">
    <%= @voucher.errors.full_messages %>
  </div>
<% end %>

<%= form_for @voucher do |f| %>
  <%= f.hidden_field :client_id %>
  <div class="form-group">
    <label>Expiry Date</label>
    <%= f.date_field :expiry_date %>
  </div>
  <div class="form-group">
    <label>Issue Date</label>
    <%= f.date_field :issue_date %>
  </div>
  <div class="form-group">
    <label>Original Balance (Euros)</label>
    <%= f.text_field :original_balance_in_euros %>
  </div>
  <%= f.submit %>
<% end %>

app/views/vouchers/show.html.erb
Show Voucher